{
 "title": "Kafka lag | Burrow",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "KAFKA PARTITION CURRENT OFFSET",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_burrow_partition_current_offset"
    }
   ]
  },
  {
   "title": "KAFKA TOPIC PARTITION OFFSET",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_burrow_topic_partition_offset"
    }
   ]
  },
  {
   "title": "KAFKA  PARTITION  LAG",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_burrow_partition_lag" }
   ]
  },
  {
   "title": "KAFKA PARTITION MAX OFFSET",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_burrow_partition_max_offset"
    }
   ]
  },
  {
   "title": "KAFKA TOTAL LAG",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_burrow_total_lag" }
   ]
  },
  {
   "title": "Kafka status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_burrow_status" }
   ]
  }
 ]
}